### ISSUE TITLE
Upcoming release plan and breaking changes

### ISSUE THREAD

**Issue by pinepain** [pinepain/php-v8#31]
v0.1.9 (released Sept 1, 2017):
 - no BC breaks;
 - last release that supports PHP 7.0 (issue #30);
 - methods naming moved to camelCase (PR #32).

v0.2.0 (ETA Sept 14, 2017):
 - BC-breaking API changes;
 - drop PHP 7.0 support and require PHP >= 7.1 (issue #30);
 - constants will be renamed to match PSR-2 standard;
 - snake_case methods will be removed to match PSR-2 standard;
 - method names that overlap with PHP keywords are the subject of renaming;
 - `V8\Exception` class as well as it methods is the subject of further renaming;

TL;DR

Upcoming release v0.1.9 will be the last release that support PHP 7.0. Starting from v0.2.0 release PHP >= 7.1 required. *All comments, requests and suggesting about this should go to #30 issue*.

In the upcoming v0.1.9 release I plan to start moving extension public API closer to PHP world which means it become more PSR-2 compatible, especially method names get converted from PascalCase (UpperCamelCase) to typical camelCase (LowerCamelCase) which is not the big issue as PHP is quite lenient to identifiers case. That's not the case for constants, which are often named in camelCase in V8 - I'll rename them to UPPER_UNDERSCORE. Some snake_case methods (notably, `HeapStatistics` methods will be renamed to camelCase.

Note, that this list of changes is incomplete, however, I'll try to keep you updated on progress and share further ideas and decisions.

As I'm also developer and a bit in ops, I know how crucial is to have stable API you can rely on and how BC-breaks hurt business.

That's why I have an upcoming surprise for you to let you abstract from v8 internals and just get things done. Stay tuned.

In a while I'll make legacy PPA for those who prefer stability and can't follow current release plan and adapt wild changes.

**Comment by k42b3** [comment]
@pinepain thx for the notice! Yes Iam still using php-v8 and its working great. As you may know I have wrote a small lib to handle all the php <-> v8 type juggling. I think it would be great to have some of the functionallity directly in this extension i.e.: 
https://github.com/apioo/psx-v8/blob/master/src/Encoder.php or 
https://github.com/apioo/psx-v8/blob/master/src/Decoder.php 

So Iam looking forward to the surprise to abstract away these v8 details.

**Comment by pinepain** [comment]
@k42b3 indeed. Here is some teaser what will available to extract v8 value to php (decode in terms of your library):

Available extractors:
 - raw
 - array
 - primitive
 - string
 - number
 - bool
 - null
 - undefined
 - regexp
 - date
 - datetime
 - object
 - function
 - instance
 - assoc
 - scalar

Concepts:
 - [x] array, array(<type>)
 - [x] assoc
 - [x] string
 - [x] primitive
 - [x] primitive(string)
 - [x] scalar
 - [x] scalar(string)
 - [x] number 
 - [x] int (integer)
 - [x] float (decimal)
 - [x] bool (boolean)
 - [x] null
 - [x] undefined
 - [x] regexp, regexp(string) - to extract only pattern without flags
 - [x] date -> float?
 - [x] datetime -> will be converted to DateTime
 - [x] function
 - [ ] raw:function -> reverse-wrapped function
 - [x] object
 - [x] object(string)
 - [x] instance()
 - [x] instance(Php\Namespaced\ClassName)
 - [x] raw
 - [x] raw(string)
 - [x] raw(object) -> raw object
 - [ ] raw(function) -> raw function
 - [x] string|number
 - [x] array(string|number)
 - [x] array(object(string))

The list above is incomplete and may be out of date and changed in the future at all.

**Comment by pinepain** [comment]
As there is nothing more to add, will close this thread. Will post more on update and wrapper library release.

**Comment by pinepain** [comment]
To freeze current PPA packages I created https://launchpad.net/~pinepain/+archive/ubuntu/php-legacy ppa. This PPA **won't** be updated ever and eventually may be a subject of silent removal without any previous warning. Use at your own risk.

**Comment by pinepain** [comment]
Hi! Short status update: v0.2.0 release tagged.

In advance, I published wrapper library for php-v8 - https://github.com/pinepain/php-v8-js-sandbox/tree/wip-public-release. The work is still in progress, so feels free to suggest changes and ask questions. It was made for my side projects needs and you may find ad-hoc solutions there. If you will be lucky to do that, I would appreciate if you report that to me. Also, feels free to ask questions: the doc and tests are not the strongest part and they are also in WIP state.

If you like what I'm doing and you use it in you work, I'd love if you [support me on Patreon](https://www.patreon.com/pinepain). I have plenty ideas and improvements in mind, but doing all that over evenings and weekends is not sustainable in the long term.
